/*----------------------------------------------------------------------------*/
/* Copyright (c) 2018 FIRST. All Rights Reserved.                             */
/* Open Source Software - may be modified and shared by FRC teams. The code   */
/* must be accompanied by the FIRST BSD license file in the root directory of */
/* the project.                                                               */
/*----------------------------------------------------------------------------*/

package frc.robot.commands;

import edu.wpi.first.wpilibj.command.Command;

import edu.wpi.first.wpilibj.PIDController;
import edu.wpi.first.wpilibj.PIDSourceType;
import edu.wpi.first.wpilibj.command.PIDCommand;
import frc.robot.Robot;


public class PIDStraight extends PIDCommand {
  double dist;
  public PIDStraight(double theDist) {

    super("PIDStraight", 1.0, 0.0, 0.0, 0.02);
    getPIDController().setContinuous(false);
    getPIDController().setAbsoluteTolerance(0.5);
    getPIDController().setSetpoint(theDist);
    getPIDController().setOutputRange(-0.5, 0.5);
    dist = theDist;
    // Use requires() here to declare subsystem dependencies
    // eg. requires(chassis);
    requires(Robot.driveSub);
  }



  
  @Override
  protected double returnPIDInput() {
      // Return your input value for the PID loop
      // e.g. a sensor, like a potentiometer:
      // yourPot.getAverageVoltage() / kYourMaxVoltage;

      // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SOURCE
      
      double distTraveled = dist - (Robot.driveSub.getRightEncoderDistance()/18.849);
      return distTraveled;

      //may be getting wrong thing, check later

      // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SOURCE
  }

  @Override
  protected void usePIDOutput(double output) {
      // Use output to drive your system, like a motor
      // e.g. yourMotor.set(output);
      Robot.driveSub.setRight(output);
      Robot.driveSub.setLeft(output * -1);
      // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=OUTPUT

      // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=OUTPUT
  }



  // Called just before this Command runs the first time
  @Override
  protected void initialize() {
    Robot.driveSub.resetLeftEncoder();
    Robot.driveSub.resetRightEncoder();

    
  }

  // Called repeatedly when this Command is scheduled to run
  @Override
  protected void execute() {

  }

  // Make this return true when this Command no longer needs to run execute()
  @Override
  protected boolean isFinished() {
    if((dist - (Robot.driveSub.getRightEncoderDistance()/14.3)) >= dist)
    {
      System.out.println("finished move forward");
      return true;
    }else{
      System.out.println("has moved:" + (Robot.driveSub.getRightEncoderDistance()/18.849) + "in");

      return false;
    }
  }

  // Called once after isFinished returns true
  @Override
  protected void end() {
    getPIDController().disable();
    Robot.driveSub.resetLeftEncoder();
    Robot.driveSub.resetRightEncoder();
  }

  // Called when another command which requires one or more of the same
  // subsystems is scheduled to run
  @Override
  protected void interrupted() {
    end();
  }
}
